package com.rick.supertrading.domain.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import org.hibernate.annotations.CreationTimestamp;

import java.time.Instant;

/**
 * One bot run for a {@link Schedule}.
 *
 * <p>The {@code idempotency_key} (unique) is generated by the scheduler trigger
 * and carried through SQS; it is the hard guarantee against double-recording when
 * a job is delivered more than once.
 */
@Entity
@Table(name = "execution")
public class Execution {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "schedule_id", nullable = false)
    private Schedule schedule;

    @CreationTimestamp
    @Column(name = "started_at", nullable = false, updatable = false)
    private Instant startedAt;

    @Column(name = "ended_at")
    private Instant endedAt;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private ExecutionStatus status = ExecutionStatus.RUNNING;

    @Column(name = "error_message")
    private String errorMessage;

    @Column(name = "screenshot_s3_key")
    private String screenshotS3Key;

    @Column(name = "idempotency_key", unique = true, length = 100)
    private String idempotencyKey;

    protected Execution() {
        // for JPA
    }

    public Execution(Schedule schedule, String idempotencyKey) {
        this.schedule = schedule;
        this.idempotencyKey = idempotencyKey;
    }

    /** Mark this run as completed successfully. */
    public void markSuccess() {
        this.status = ExecutionStatus.SUCCESS;
        this.endedAt = Instant.now();
    }

    /** Mark this run as failed, recording the error and (optional) screenshot key. */
    public void markFailed(String errorMessage, String screenshotS3Key) {
        this.status = ExecutionStatus.FAILED;
        this.errorMessage = errorMessage;
        this.screenshotS3Key = screenshotS3Key;
        this.endedAt = Instant.now();
    }

    public Long getId() {
        return id;
    }

    public Schedule getSchedule() {
        return schedule;
    }

    public Instant getStartedAt() {
        return startedAt;
    }

    public Instant getEndedAt() {
        return endedAt;
    }

    public ExecutionStatus getStatus() {
        return status;
    }

    public String getErrorMessage() {
        return errorMessage;
    }

    public String getScreenshotS3Key() {
        return screenshotS3Key;
    }

    public String getIdempotencyKey() {
        return idempotencyKey;
    }
}
